name: Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2021.03.31'

      - uses: actions/checkout@v1

      - name: Run linter
        run: clj-kondo --lint src test

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Run tests
        run: lein test

  compile-java:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Compile Java
        run: lein javac

      - name: Store compiled artifacts
        uses: actions/upload-artifact@v2
        with:
          name: classes
          path: |
            project.clj
            src/clojure
            target/classes

  jar:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
      - compile-java
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: classes
          path: .

      - name: Package JAR
        run: lein jar

      - name: Store JAR
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/*.jar
