name: Test

on: [ push, pull_request ]

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}

      - name: Download dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: lein deps

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2021.03.31'

      - uses: actions/checkout@v1

      - name: Run linter
        run: ./bin/lint.sh

  test:
    runs-on: ubuntu-latest
    needs:
      - deps
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}

      - name: Run tests
        run: lein -o with-profile compile,dev test

  test-deploy:
    runs-on: ubuntu-latest
    needs:
      - deps
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.3.814'

      # FIXME: although it helps a bit, this is not using the deps.edn deps of this subproject
      - name: Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}

      - name: Run tests
        run: ./deploy/bin/test.sh

  test-example:
    runs-on: ubuntu-latest
    needs:
      - deps
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.3.814'

      # FIXME: although it helps a bit, this is not using the deps.edn deps of this subproject
      - name: Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}

      - name: Run tests
        run: clojure -Sdeps '{:replace-deps {nl.epij/google-cloud-functions-ring-adapter {:local/root ".."}}}' -M:test
        working-directory: example

  publish-snapshot:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
      - test-deploy
      - test-example
    steps:
      - name: Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}

      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Deploy JAR
        env:
          CLOJARS_USER: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASS: ${{ secrets.CLOJARS_PASSWORD }}
        run: lein with-profile compile,dev deploy clojars
